name: 这是一个测试配置

on: 
  schedule:
  - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  build:
    name: My Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Hello, world!!!!!!!
    
    - name: Run a one-line script
      run: curl http://linhai.epizy.com/getip.php
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo 测试多行
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
